version: '3.8'

services:
  db:
    build: .
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./build/migrations:/docker-entrypoint-initdb.d
