name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
    paths: [ 'Dockerfile', 'docker-compose.yaml' ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the App image
      run: docker build . --file Dockerfile --target app --tag jaws:latest
    - name: Build the App image
      run: docker build . --file Dockerfile --target psql --tag jaws:latest
