name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
    paths: [ 'Dockerfile', 'docker-compose.yaml', '.github/workflows/docker-image.yml' ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the App image
      run: docker build . --file Dockerfile --target app --tag jaws-app:latest
    - name: Build the Postgres image
      run: docker build . --file Dockerfile --target app --tag jaws-psql:latest

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Verify docker installation
      run: |
          docker --version
    - name: Build the Docker images
      run: docker compose build